import {
  ShoppingCart,
  Train,
  Package,
  Zap,
  Heart,
  Utensils,
  Gamepad2,
  TrendingUp,
  CircleDot,
  Tv,
  Store,
  ShoppingBasket,
  Scissors,
  Dumbbell,
  Users,
  Shirt,
  Building2,
  Shield,
  BookOpen,
  Plane,
  Tag,
  Wallet,
  Car,
  Coffee,
  Music,
  Baby,
  PawPrint,
  type LucideIcon,
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  食費: ShoppingCart,
  食料品: ShoppingCart,
  スーパー: ShoppingBasket,
  外食: Utensils,
  カフェ: Coffee,
  コンビニ: Store,
  交通費: Train,
  電車: Train,
  バス: Train,
  タクシー: Car,
  ガソリン: Car,
  車: Car,
  日用品: Package,
  雑費: Package,
  光熱費: Zap,
  電気代: Zap,
  ガス代: Zap,
  水道代: Zap,
  '医療・健康': Heart,
  医療費: Heart,
  医療: Heart,
  健康: Heart,
  薬局: Heart,
  娯楽: Gamepad2,
  ゲーム: Gamepad2,
  音楽: Music,
  サブスク: Tv,
  サブスクリプション: Tv,
  動画配信: Tv,
  交際費: Users,
  飲み会: Users,
  被服費: Shirt,
  衣服: Shirt,
  洋服: Shirt,
  美容院: Scissors,
  美容: Scissors,
  ヘアサロン: Scissors,
  ジム: Dumbbell,
  スポーツ: Dumbbell,
  家賃: Building2,
  住居費: Building2,
  保険: Shield,
  教育: BookOpen,
  書籍: BookOpen,
  本: BookOpen,
  旅行: Plane,
  収入: TrendingUp,
  給料: Wallet,
  副収入: Wallet,
  ボーナス: Wallet,
  子育て: Baby,
  ペット: PawPrint,
  その他: CircleDot,
}

export function getCategoryIcon(categoryName: string): LucideIcon {
  return MAP[categoryName] ?? Tag
}
